#! /bin/sh

# autostart
sxhkd -c .config/sxhkd/sxhkdrc &
xrdb ~/.Xresources
nitrogen --restore
compton &
redshift &
lxpolkit &
polybar top &

# desktops/workspaces
bspc monitor -d 1 2 3 4 5 6

# gaps and padding
bspc config window_gap			20
bspc config top_padding 		40

# borders
bspc config border_width		2
bspc config focused_border_color	"#D8DEE9"
bspc config normal_border_color		"#2E3440"
bspc config presel_feedback_color	"#D8DEE9"

# window settings
bspc config split_ratio          	0.50
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_by_distance    	true
bspc config history_aware_focus  	true
bspc config click_to_focus 	 	true

# rules
bspc rule -a qutebrowser desktop=^1
bspc rule -a Firefox desktop=^1
bspc rule -a Emacs desktop=^2 state=tiled
bspc rule -a discord desktop=^3
bspc rule -a Steam desktop=^4 state=floating
bspc rule -a Spotify desktop=^5
bspc rule -a Gimp-2.8 desktop=^6 state=floating
bspc rule -a Gnome-calendar state=floating
bspc rule -a Nemo state=floating
